### ISSUE TITLE
Way to get marker visibility

### ISSUE THREAD

**Issue by ntngl** [YUzhva/react-leaflet-markercluster#82]
Hi. Is there a way to detect if marker visible separately or it in cluster?

**Comment by YUzhva** [comment]
There should be some actions when you will start that detection. Action, like: click, mouse hover, initial rendering.

In what case you would like to know it?

**Comment by ntngl** [comment]
Sorry to bother you, I solved the problem differently. I took the package [supercluster](https://github.com/mapbox/supercluster), calculate clusters and points and render custom components without using react-leaflet-markercluster.

The case was in drawing custom markers with additional info in vector layer if it not in cluster

**Comment by BrandtNick** [comment]
Hi, sorry to hijack this thread (almost a year later though) but I think this is something I need to solve my problem. I'm having problems with draggable markers in react-leaflet-markercluster and the reason is that the markers that are hidden in clusters gets undefined when leaflet tries to access them to make them draggable. 

I would like to know how I can detect if a marker is in a cluster, on click event. 

Thanks in advance,
Nick
